### ISSUE TITLE
Migrations on multiple shards broken in rails 3.2

### ISSUE THREAD

**Issue by NielsKSchjoedt** [thiagopradi/octopus#110]
When doing a migration e.g.:

``` ruby
class AddIndexToFailedAdvertsCreatedAt < ActiveRecord::Migration
  using_group(:shards)

  def change
    add_index :failed_adverts, :created_at
  end
end
```

It only adds the migration-id (schema-migrations) to the database that is set as master-shard, unless I use the changes made in this fork:
https://github.com/Agilysys/octopus

BTW i'm on 3.2.6 and my shards.yml looks like this:

``` yaml
octopus:
  verify_connection: true
  environments:
    - development
    - production
  development:
    shards:
      da:
        adapter: postgresql
        encoding: utf8
        database: dk_development
        username: postgres
        password: postgres
        template: template0 # Required for UTF8 encoding
        pool: 25
      se:
        adapter: postgresql
        encoding: utf8
        database: se_development
        username: postgres
        password: postgres
        template: template0 # Required for UTF8 encoding
        pool: 25
```
