### ISSUE TITLE
after_initialize hook and current_shard method failure

### ISSUE THREAD

**Issue by NielsKSchjoedt** [thiagopradi/octopus#111]
I'm on rails 3.2.6, and I'm experiencing a strange problem, when I load objects from the db (postgres). I have a model like so:

``` ruby
class Advert < ActiveRecord::Base
   include CountryRecord

  # Relationships
  belongs_to :car, :touch => true
  belongs_to :seller
end
```

And the CountryRecord looks like this:

``` ruby
class UnknownCountryShard < Exception; end
module CountryRecord
  extend ActiveSupport::Concern

  included do
    attr_reader :country
    after_initialize :set_country
  end

  private

  def set_country
    @country = current_shard
    raise UnknownCountryShard.new("Unknown country shard '#{@country}'") unless [:da, :se].include?(@country)
  end
end
```

Now when I open the console in PRODUCTION, and I do something like this:

``` ruby
Advert.using(:da).where(:url => 'http://www.someurl.com')
```

I recieve the following error:

```
UnknownCountryShard: Unknown country shard 'master'
    from /app/lib/country_record.rb:14:in `set_country'
    from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:409:in `_run__726855266692006148__initialize__420928863111078875__callbacks'
    from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:385:in `_run_initialize_callbacks'
    from /app/vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.6/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/base.rb:524:in `init_with'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/inheritance.rb:68:in `instantiate'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/querying.rb:38:in `block (2 levels) in find_by_sql'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/querying.rb:38:in `collect!'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/querying.rb:38:in `block in find_by_sql'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/explain.rb:40:in `logging_query_plan'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/querying.rb:37:in `find_by_sql'
    from /app/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.3.5/lib/new_relic/agent/method_tracer.rb:491:in `block in find_by_sql_with_trace_ActiveRecord_self_name_find_by_sql'
    from /app/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.3.5/lib/new_relic/agent/method_tracer.rb:242:in `trace_execution_scoped'
    from /app/vendor/bundle/ruby/1.9.1/gems/newrelic_rpm-3.3.5/lib/new_relic/agent/method_tracer.rb:486:in `find_by_sql_with_trace_ActiveRecord_self_name_find_by_sql'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/relation.rb:171:in `exec_queries'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/relation.rb:160:in `block in to_a'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/explain.rb:40:in `logging_query_plan'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/relation.rb:159:in `to_a'
    from /app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/relation.rb:498:in `inspect'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/commands/console.rb:47:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/commands/console.rb:8:in `start'
    from /app/vendor/bundle/ruby/1.9.1/gems/railties-3.2.6/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'irb
```

However when I do it in DEVELOPMENT, I receive the following:

```
#<Octopus::ScopeProxy:0x007fbf5d5d26a8 @shard=:da, @klass=[]>
```

But if I add a ".first" to the call, like so:

``` ruby
Advert.using(:da).where(:url => 'http://www.someurl.com').first
```

Then I get the record I need!

My shards.yml looks like this:

``` yaml
octopus:
  verify_connection: true
  environments:
    - development
    - production
  development:
    shards:
      da:
        adapter: postgresql
        encoding: utf8
        database: au_dk_development
        username: postgres
        password: postgres
        template: template0 # Required for UTF8 encoding
        pool: 25
      se:
        adapter: postgresql
        encoding: utf8
        database: au_se_development
        username: postgres
        password: postgres
        template: template0 # Required for UTF8 encoding
        pool: 25
 production:
    shards:
      da:
        adapter:    postgresql
        encoding:   utf8
        template:   template0 # Required for UTF8 encoding
        pool:       20
        database:   xxx
        username:  xxx
        password:   xxx
        host:       ip
        port:       5432
      se:
        adapter:    postgresql
        encoding:   utf8
        template:   template0 # Required for UTF8 encoding
        pool:       20
        database:   xxx
        username:  xxx
        password:   xxx
        host:       ip
        port:       5432
```
