### ISSUE TITLE
Setting pool size on heroku

### ISSUE THREAD

**Issue by NielsKSchjoedt** [thiagopradi/octopus#114]
I have a shards.yml that looks like this:

``` yaml
octopus:
  verify_connection: true
  environments:
    - development
    - production
  development:
    shards:
      da:
        adapter: postgresql
        encoding: utf8
        database: db
        username: postgres
        password: postgres
        template: template0 # Required for UTF8 encoding
        pool: 15
      se:
        adapter: postgresql
        encoding: utf8
        database: db
        username: postgres
        password: postgres
        template: template0 # Required for UTF8 encoding
        pool: 15
  production:
    shards:
      da:
        adapter:    postgresql
        encoding:   utf8
        template:   template0 # Required for UTF8 encoding
        pool:       15
        database:   db
        username:   user
        password:   pass
        host:       ip
        port:       5432
      se:
        adapter:    postgresql
        encoding:   utf8
        template:   template0 # Required for UTF8 encoding
        pool:       15
        database:   db
        username:   user
        password:   pass
        host:       ip
        port:       5432
```

If I open a console and do this:

``` ruby
Car.using(:da).connection_config
=> #<Octopus::ScopeProxy:0x000000080450d0 @shard=:da, @klass={"adapter"=>"postgresql", "encoding"=>"utf8", "template"=>"template0", "pool"=>15, "database"=>"db", "username"=>"user", "password"=>"pass", "host"=>"ip", "port"=>5432, "octopus_shard"=>"da"}>
```

It seems that the pool size is correctly set. However I get a lot of these errors?

```
# (ActiveRecord::ConnectionTimeoutError) "could not obtain a database connection within 5 seconds (waited 5.059564758 seconds). The max pool size is currently 5; consider increasing it."

/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:252:in `block (2 levels) in checkout'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in `loop'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in `block in checkout'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:233:in `checkout'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:96:in `block in connection'
/app/vendor/ruby-1.9.3/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/app/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:95:in `connection'
```

Any idea why?

**Comment by Geesu** [comment]
Sorry to open an old thread, but I'm currently running into a similar problem with Octopus `0.8.5`, sidekiq `3.3.0`, and rails `4.1.2`.  Basically my sidekiq worker constantly throws `ActiveRecord::ConnectionNotEstablished`.

The master connection has the correct pool size (250), and setting the pool size in the initializer doesn't actually help:
https://gist.github.com/Geesu/d1450ade1640e05dfe39

And the resulting info on the connection:
```[1] pry(main)> ActiveJob.connection.instance_eval{ @shards }['slave1'].instance_eval{@spec}
=> #<ActiveRecord::ConnectionAdapters::ConnectionSpecification:0x00000108bc4360
 @adapter_method="postgresql_connection",
 @config={"pool"=>30, "adapter"=>"postgresql", "database"=>"database", "username"=>"uesrname", "password"=>"password", "host"=>"example.com", "octopus_shard"=>"slave1"}>```

**Comment by swordfish444** [comment]
@TheCorp @thiagopradi I'm seeing 1000s of these errors with Puma and Octopus in production. We have 2 shards, a master and readonly. Puma is configured to 4 workers and 8 threads. This provides enough buffer for 8 connections to the master and 8 to the readonly. However, I believe they are shared. 

Why would we still be experiencing these errors?

Here is what our shard configuration looks like.

```yaml
    master:
      pool: 16
      ...
    readonly:
      pool: 16
      ...
```

@thiagopradi This issue should be opened back up.


`Octopus 0.9.2  |  Rails 5.1.5`
