### ISSUE TITLE
Spork cucumber Tests - no reads from replicas

### ISSUE THREAD

**Issue by ausangshukla** [thiagopradi/octopus#120]
If I launch the rails console in the test env - octopus handles reads from the replica and writes to the master. No issues here.

However if i run my cucumber tests with the spork gem then slaves are never used - only the master is hit for both reads and writes. Do I need to do anything special to get octopus working with spork/cucumber ?

My shards.yml is as follows

``` yaml
octopus:
  replicated: true
  environments:
    - development
    - production
    - test

  production:
    shards:
      slave1:
        adapter: mysql2
        host: aaa
        database: xxx
        username: root
        password: root
        pool: 5
        encoding: utf8
        reconnect: true   

  development:
    shards:
      slave2:
        adapter: mysql2
        host: bbb
        database: xxx
        username: root
        password: root
        pool: 5
        encoding: utf8
        reconnect: true  

  test:
    shards:
      slave3:
        adapter: mysql2
        host: ccc
        database: xxx
        username: root
        password: root
        pool: 5
        encoding: utf8
        reconnect: true  
```
