### ISSUE TITLE
Spike in error rates after phusion passenger restart

### ISSUE THREAD

**Issue by idlecool** [thiagopradi/octopus#153]
I have been running octopus in production for last 24 hours. I have noticed a spike in error rates during a webserver restart. Which we usually do after a prod push.

The errors are mostly because of two reasons:
1. Mysql2::Error: Lost connection to MySQL server during query: <ANY MYSQL QUERY>
2. undefined method `<field name>' for nil:NilClass

As we use passenger, I have this block in environment.rb:

```
if defined?(PhusionPassenger)
  PhusionPassenger.on_event(:starting_worker_process) do |forked|
    if forked
        ActiveRecord::Base.connection_proxy.instance_variable_get(:@shards).each {|k,v| v.clear_reloadable_connections! }
    end
  end
else
    ActiveRecord::Base.connection_proxy.instance_variable_get(:@shards).each {|k,v| v.clear_reloadable_connections! }
end
```

I am just using db replication, and no shard-ing, my shards.yml looks like:

```
octopus:
    replicated: true
    fully_replicated: true
    verify_connection: true
    production:
        slave1:
            adapter: mysql2
            host: <hash>.us-east-1.rds.amazonaws.com
            database: <db>
            username: <user>
            password: <password>
            session_variables: time_zone=UTC
            reconnect: true
        slave2:
            adapter: mysql2
            host: <hash>.us-east-1.rds.amazonaws.com
            database: <db>
            username: <user>
            password: <password>
            session_variables: time_zone=UTC
            reconnect: true
```

We have 15 webservers behind Amazon Load balancer. Production push happens in two equal batches.

Each batch push includes following steps:
1. Detach Webservers from load balancer (Takes 30-60 seconds)
2. Rsync code
3. Restart Passenger
4. Run curl on each webserver individually
5. Attach Webservers back to the load balancer

The error rate is around 0.3% of total request. Which is bad. Can anyone tell how I can fix this?
