### ISSUE TITLE
Replication Leads to Performance Failures on Heroku Postgres

### ISSUE THREAD

**Issue by nmagedman** [thiagopradi/octopus#154]
I've been experimenting with using Octopus for master/slave replication,
however the performance is... sub-optimal.   Everything works fine without Octopus,
but once I enable it, I start getting frequent timeout errors.

I'm using Heroku Postgres with one slave (here, named 'onyx') following the master.
Things work fine initially, but within minutes dynos start timing out.
Once they start timing out, they snowball, repeatedly timing out.

I am not explicitly using Octopus within my rails code (i.e. `.using()`).  I'm just bundling it within the Gemfile
and enabling replication in shards.yml.

My shards.yml file is:

```
octopus:
  environments:
    - production

  replicated: true
  production:
    onyx:
      adapter: postgresql
      encoding: unicode
      pool: 5
      database: dxxxxxxxxxxxxx
      username: uxxxxxxxxxxxxx
      password: "pxxxxxxxxxxxxxxxxxxxxxxxxx"
      host: ec2-123-123-123-123.compute-1.amazonaws.com
      port: 5432
```

I've experimented with various releases of Octopus, pulled directly from the repo, including the latest (e395360334920dd797bfa975812e6f871c3a0802)

rails 3.2.11
unicorn 4.5.0
newrelic_rpm 3.5.5.38

Any suggestions on how to debug this?
