### ISSUE TITLE
Replication not using read slaves. 

### ISSUE THREAD

**Issue by radfahrer** [thiagopradi/octopus#155]
I just setup a test app with the following configuration: 

``` yaml
octopus:
  replicated: true
  development:
    slave1:
      adapter: sqlite3
      host:     localhost
      database: db/shard.sqlite3
```

In rails console I get

``` sh
1.9.3p327 :012 > Octopus.environments
 => ["production"]
```

Also  my queries don't seem to be hitting the slave. What's going on? shouldn't development be in environments?
