### ISSUE TITLE
Reads not being redirected - postgres

### ISSUE THREAD

**Issue by kerr23** [thiagopradi/octopus#158]
Gemfile:
gem "ar-octopus", :git => "git://github.com/tchandy/octopus.git", :require => "octopus"

config/shards.yml:

``` yaml:
octopus:
  fully_replicated: true
  environments:
    - development:
  development:
    slave1:
      adapter: postgresql
      host: dbslave
      database: db1
```

I understand from the docs that fully_replicated means that all reads should go to the slave.
I assume this means that I don't have to add   replicated_model() to all of my models correct?
I read in one of the examples that transactions would be re-directed to the master regardless, is that still the case? https://github.com/tchandy/octopus_replication_example

Thanks
