### ISSUE TITLE
Getting credential mixup between Rails environments

### ISSUE THREAD

**Issue by scottriding** [thiagopradi/octopus#26]
I'm using shard-selection in my migrations. During the development process, all has been hunky-dory. But I recently started setting up the production database using shard.yml:

```
octopus:
  environments:
    - development
    - production
  development:
    first_shard:
      host: localhost
      adapter: mysql2
      user: root
      database: dev_first
    second_shard:
      host: localhost
      adapter: mysql2
      user: root
      database: dev_second
  production:
    first_shard:
      host: [Amazon RDS endpoint]
      adapter: mysql2
      user: [Amazon username]
      password: [Amazon password]
      database: prod_first
    second_shard:
      host: [Amazon RDS endpoint]
      adapter: mysql2
      user: [Amazon username]
      password: [Amazon password]
      database: prod_second
```

When I do migrations on non-sharded models, they go through just fine. But when my sharded migrations run, I get a credential error. 

```
Access denied for user 'root'@'[IP address]' (using password: NO)
```

It appears that the sharded migrations are attempting to use the development credentials on the production database (using 'root' as a username), even though the system is running in production mode.

Any ideas?
