### ISSUE TITLE
rake db:test:prepare destroys test schema when development shards are defined

### ISSUE THREAD

**Issue by chrisb87** [thiagopradi/octopus#31]
With the following shards.yml:

```
octopus:
  replicated: true
  fully_replicated: true

  environments:
      - production
      - development

  development:
    slave1:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: cornice_development
      pool: 5
      username: root
      password: 
      #socket: /tmp/mysql.sock
      host: localhost

  production:
    slave1:
```

My test database is wiped clean, including the schema, when I try to the rspec test suite or "rake db:test:prepare". If I remove the development entries from shards.yml, db:test:prepare correctly loads the schema in schema.rb into the test database.
