### ISSUE TITLE
rake db:migrate should run only on master (shouldn't try to run on slaves)

### ISSUE THREAD

**Issue by ecylmz** [thiagopradi/octopus#353]
I have fully replicated MySQL Master-Slave databases. I just want to run `rake db:migrate` command on master shard.

If `Octopus` try to run `rake db:migrate` command on `slaves`, MySQL Slaves stop working.

My migration files and models not include any `using(:shard)` blocks.

I just want to send all write queries and migration commands to master, and all reads queries to slaves. MySQL is handling replication job.

Detailed information are listed below.

Problem steps:

- run `rake db:migrate RAILS_ENV=development`
- Octopus try to run migration command. Trying order: (slave1, slave2, slave3, master) (I dont want to run migration command on slaves but Octopus trying...)
- This time MySQL slaves stop working. Because MySQL configured as slaves.

Example MySQL Error:

```text
[ERROR] Slave SQL: Error 'Table 'schema_migrations' already exists' on query. Default database: 'ustad_development'. Query: 'CREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL) ENGINE=InnoDB', Error_code: 1050

[Warning] Slave: Table 'schema_migrations' already exists Error_code: 1050

[ERROR] Error running query, slave SQL thread aborted. Fix the problem, and restart the slave SQL thread with "SLAVE START". We stopped at log 'mysql
-bin.000001' position 310
```

As a result, I just want to run `rake db:migrate` command on master shard. What am i missing?

```yaml
# config/shards.yml

octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development

  development:
    slave1:
      adapter: mysql2
      encoding: utf8
      pool: 10
      username: <%= ENV['MYSQL_SLAVE_1_ENV_MYSQL_USER'] %>
      password: <%= ENV['MYSQL_SLAVE_1_ENV_MYSQL_PASS'] %>
      host: <%= ENV['MYSQL_SLAVE_1_PORT_3306_TCP_ADDR'] %>
      port: <%= ENV['MYSQL_SLAVE_1_PORT_3306_TCP_PORT'] %>
      database: foo_development
    slave2:
      adapter: mysql2
      encoding: utf8
      pool: 10
      username: <%= ENV['MYSQL_SLAVE_2_ENV_MYSQL_USER'] %>
      password: <%= ENV['MYSQL_SLAVE_2_ENV_MYSQL_PASS'] %>
      host: <%= ENV['MYSQL_SLAVE_2_PORT_3306_TCP_ADDR'] %>
      port: <%= ENV['MYSQL_SLAVE_2_PORT_3306_TCP_PORT'] %>
      database: foo_development
    slave3:
      adapter: mysql2
      encoding: utf8
      pool: 10
      username: <%= ENV['MYSQL_SLAVE_3_ENV_MYSQL_USER'] %>
      password: <%= ENV['MYSQL_SLAVE_3_ENV_MYSQL_PASS'] %>
      host: <%= ENV['MYSQL_SLAVE_3_PORT_3306_TCP_ADDR'] %>
      port: <%= ENV['MYSQL_SLAVE_3_PORT_3306_TCP_PORT'] %>
      database: foo_development
```

```yaml
# config/database.yml

production:
  adapter: mysql2
  encoding: utf8
  pool: 10
  database: foo
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  host: <%= Rails.application.secrets.database['host'] %>
  port: <%= Rails.application.secrets.database['port'] %>

development:
  adapter: mysql2
  encoding: utf8
  pool: 10
  database: foo_development
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  host: <%= Rails.application.secrets.database['host'] %>
  port: <%= Rails.application.secrets.database['port'] %>

test:
  adapter: mysql2
  encoding: utf8
  pool: 10
  database: foo_test
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  host: <%= Rails.application.secrets.database['host'] %>
  port: <%= Rails.application.secrets.database['port'] %>
```

@sobrinho: Can you help me? :(
