### ISSUE TITLE
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  cannot drop the currently open database

### ISSUE THREAD

**Issue by noff** [thiagopradi/octopus#361]
Hello.
Rails 4.2.5.
Octopus used for sharding.
PostgreSQL 9.4 for database.

When run
```RAILS_ENV=test rake db:test:load_schema```

Receive this error:
```
$ RAILS_ENV=test rake db:test:load_schema
rake aborted!
ActiveRecord::StatementInvalid: PG::ObjectInUse: ERROR:  cannot drop the currently open database
: DROP DATABASE IF EXISTS "rdb_test"
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/ar-octopus-0.8.6/lib/octopus/abstract_adapter.rb:15:in `instrument'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:86:in `drop_database'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/ar-octopus-0.8.6/lib/octopus/proxy.rb:303:in `method_missing'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:28:in `drop'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:41:in `purge'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:163:in `purge'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:356:in `block (3 levels) in <top (required)>'
/Users/noff/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/noff/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
PG::ObjectInUse: ERROR:  cannot drop the currently open database
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/ar-octopus-0.8.6/lib/octopus/abstract_adapter.rb:15:in `instrument'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql/schema_statements.rb:86:in `drop_database'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/ar-octopus-0.8.6/lib/octopus/proxy.rb:303:in `method_missing'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:28:in `drop'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/tasks/postgresql_database_tasks.rb:41:in `purge'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/tasks/database_tasks.rb:163:in `purge'
/Users/noff/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.5/lib/active_record/railties/databases.rake:356:in `block (3 levels) in <top (required)>'
/Users/noff/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/Users/noff/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:test:load_schema => db:test:purge
(See full trace by running task with --trace)
```

How to avoid it?

**Comment by noff** [comment]
Any updates?

**Comment by miketrewartha** [comment]
@noff, did you ever find anything that was causing this for you or that fixed it?

**Comment by noff** [comment]
No. It's not fixed and I can't do experiments on production server.

**Comment by miketrewartha** [comment]
@noff, we wasted many hours on this yesterday. Thankfully, we ended up finding that we were missing the `shards` key in the YML file. So, instead of the shards.yml you have above, use this:

```
octopus:
  environments:
    - test
  shards:
    test:
      shard_0:
        database: rdb_shard_0_test
        host: localhost
        username: <%= ENV['PG_USER'] %>
        password: <%= ENV['PG_PASSWORD'] %>
        adapter: postgresql
        encoding: unicode
        pool: 5
        timeout: 5000
        port: 5432
      shard_1:
        database: rdb_shard_1_test
        host: localhost
        username: <%= ENV['PG_USER'] %>
        password: <%= ENV['PG_PASSWORD'] %>
        adapter: postgresql
        encoding: unicode
        pool: 5
        timeout: 5000
        port: 5432
```
