### ISSUE TITLE
Rails DB and Gem using octopus

### ISSUE THREAD

**Issue by warp-linden** [thiagopradi/octopus#362]
A bit complex, but let me explain

* I have a rails 3.2 app with it's own db.
* Separately I have a gem that use octopus for sharding against a separate legacy database.  

The gem by itself is able to connect and the .using(:shard_name) works perfectly.  When I include this gem into rails app the .using(:shard_name) is ignored.

Is there anything special and different I have to do when octopus is included in rails?

**Comment by warp-linden** [comment]
Ok so I experiment more and adding environments to my shards.yml has fixed this issue.

```
shared: &shared
  adapter: mysql2
  encoding: utf8
  username: user
  password: pass
  database: legacy_shard_db
  port: 3306

octopus:
  replicated: false
  fully_replicated: false
  environments:
    - development
  development:
    my_shard:
      <<: *shared
      host: shard1.database.host
    my_shard2:
      <<: *shared
      host: shard2.database.host
```

The issue that arises with this setup is migrations no longer work

```
Mysql2::Error: CREATE command denied to user 'user'@'10.xx.xx.xx' for table 'schema_migrations': CREATE TABLE `schema_migrations` (`version` varchar(255) NOT NULL) ENGINE=InnoDB
vendor/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `query'
xxx/vendor/ruby/1.9.1/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:245:in `block in execute'
```

are the migrations trying to run on the shards... can I disable this and have it only run on the rails db?
