### ISSUE TITLE
CREATE TABLE "schema_migrations" migration being sent to slave

### ISSUE THREAD

**Issue by adamors** [thiagopradi/octopus#363]
If a database is empty but replicated to a slave, Octopus sends the very first migration that creates the `schema_migrations` table to the slave. 
I'm using Rails 4.2.4 and tried both the 0.8.5 and master version of octopus to no avail. 

My shards.yml looks like:

```
octopus:
  environments:
    - production
  replicated: true
  fully_replicated: true
  production:
    slave1:
      adapter: postgresql
      host: <%= ENV['DB_SLAVE1_HOST'] %>
      database: <%= ENV['DB_SLAVE1_NAME'] %>
      username: <%= ENV['DB_USER'] %>
      password: <%= ENV['DB_PASSWORD'] %>
```

while database.yml:

```
default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: username
  password: password
  port: 5432
  pool: 5

production:
  <<: *default
  host: <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
```
