### ISSUE TITLE
READ requests are going to master database and not slave

### ISSUE THREAD

**Issue by sushma-unii** [thiagopradi/octopus#377]
Hi,
  I have an issue where all READ requests are queried on Master DB and not queried on Slave DB. 

Could you help me with setting up configuration so that by default the READ requests go to Slave DB. And also **without** using `User.using`. Or correct me if my understanding is wrong.

```
ruby 2.2.4

ar-octopus (0.8.6)
```

shards.yml:
=========
```
octopus:
  environments:
    - development
    - staging
    - production
  replicated: true
  fully_replicated: true
  development:
    slave1:
      adapter: postgresql
      encoding: unicode
      database: test_slave1
      pool: 5
      host: localhost
```

User model:
=========
```
class User < ActiveRecord::Base
  replicated_model
end
```

rails console:
==========
```
user = User.find 1

user.current_shard
 => :master 

user = User.where(id: 1).first()

user.current_shard
 => :master 

user = User.using(:slave1).find 1

user.current_shard
 => :slave1 
```

**Comment by simonmorley** [comment]
I have the same problem. Did you manage to resolve?

**Comment by jamesfzhang** [comment]
Same issue here. Seems like you have to use `Octopus.using(:slave) { User.first }`, which is not what the readme says.

**Comment by thiagopradi** [comment]
Hi @sushma-unii , @simonmorley, and @jamesfzhang - sorry for the late reply. I'm trying here, but I couldn't reproduce this issue. Can you provide more information? (like rails version). Thanks!

**Comment by mika-cn** [comment]
@thiagopradi I have the same problem
MyEnv:
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin15.0]
Rails 4.1.13
shards.yml:
````
octopus:
  replicated: true
  fully_replicated: false
  environments:
      - development
      - production
  development:
    slave:
      slave1:
        adapter: mysql2
        database: test_octopus
        username: root
        password: root
        pool: 20
    statistics:
      stat1:
        adapter: mysql2
        database: test_octopus
        username: root
        password: root
        pool: 20
  production:
    slave:
      slave1:
        adapter: mysql2
        database: test_octopus
        username: root
        password: root
        pool: 20
    statistics:
      stat1:
        adapter: mysql2
        database: test_octopus
        username: root
        password: root
        pool: 20

````

**Comment by bronislav** [comment]
@thiagopradi We have the same issue. We couldn't manage to get this working. We have to explicitly use `using` in some queries to decrease a load on the master.

rails 4.1

**Comment by cyaconi** [comment]
@thiagopradi we're facing the same issue, using configuration just like the readme says. 

Additionally to the posted before, when we query a model using Octopus.using(:slave1), it actually reads from slave, but when we query an ActiveRelation, it goes to master even using the Octopus.using(:slave1) clause.

rails 4.0.1

**Comment by netuoso** [comment]
@thiagopradi Same issue going on in my application. Is there any plans to resolve this?

#### Shards.yml
```
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development
  development:
    shards:
      slave1:
        username: mab_admin
        host: slave1.host.postgres
        password: somepassword
        adapter: postgresql
        database: main
      slave2:
        username: mab_admin
        host: slave2.host.postgres
        password: somepassword
        adapter: postgresql
        database: main
```

```
z = User.first
z.current_shard
=> :master

z = User.using(slave_group: :shards)
z.current_shard
=> {:slave_group=>:shards}

z = User.using(:slave1)
z.current_shard
=> :shard1

z = User.using(:slave2)
z.current_shard
=> :shard2
```

#### User model
```
class User < ActiveRecord::Base
  replicated_model
  using(slave_group: :shards)
end
```
