### ISSUE TITLE
Queries being sent to master DB when try to use slave

### ISSUE THREAD

**Issue by andyw8** [thiagopradi/octopus#402]
I'm doing some simple testing of Octopus in my development environment. I have made a copy of my development database and I'm trying to treat it as a readonly, fully-replicated DB.

I'm using Rails 3.2.22.1 with MySQL 5.7, and v0.8.6 of Octopus.

My `config/shards.yml`:

```
---
octopus:
  fully_replicated: true
  environments:
    - development
  development:
    slave1:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: myapp_replicated
      pool: 5
      username: root
      password:
      host: localhost
```
My development DB specified in `database.yml` is named `myapp_development`.

When I test from the rails console:
```
Country.using(:slave1).count
[Shard: slave1]   (0.2ms)  SELECT COUNT(*) FROM `myapp_development`.`countries`
```
Shouldn't this query go to `myapp_development` instead of `myapp_replicated`? Or have I misunderstood how the gem should work?
