### ISSUE TITLE
Allow url-format database connection

### ISSUE THREAD

**Issue by dcosson** [thiagopradi/octopus#403]
I have a configuration like the following:

```
octopus:
  replicated: true
  fully_replicated: false
  environments:
    - development
  development:
    read_follower1:
      adapter: postgresql
      url: 'postgres://my_user:password@postgres:5432/my_db'
```

When I replace `url` with the individual fields database, host, port, etc. everything works as expected, but with url it just gives me ConnectionNotEstablished. This is a valid syntax for specifying the DB in database.yml, and it makes things a bit simpler to manage to be able to specify a single env var with the full db connection parameters instead of up to 6 separate options.

It seems like Octopus should support this too.
