### ISSUE TITLE
Support for `url` in shards.yml

### ISSUE THREAD

**Issue by joshfng** [thiagopradi/octopus#418]
I love this gem, and so far with hard coded db credentials it works great! Many thanks!

I'm having issues getting a normal `url` database config to work within shards.yml

Here's my config:
```
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - development

  development:
    follower_1:
      url:  <%= ENV["FOLLOWER_1_DATABASE_URL"] %>
      encoding: unicode
```

When I try this I get the error `Please install the  adapter: gem install activerecord--adapter (cannot load such file -- active_record/connection_adapters/_adapter) (RuntimeError)`

So I tried setting `adapter: postgresql` in the config, which stops that error, but it still doesn't honor the db `url` value and tries to connect to localhost using my local system user.

Is there support for the standard `url` key/values in the shards file? This is needed to work with Heroku-like/12 factor systems that supply database information at runtime.

Any help on where I might look to solve this issue would be greatly appreciated
