### ISSUE TITLE
Necessary connection.clear_query_cache after any CRUD method?

### ISSUE THREAD

**Issue by gvanhoy** [thiagopradi/octopus#423]
I am trying to do simple replication with writes going to the master and reads going to the slaves. At the moment, after any CRUD operation, a cached query is used to display updated information and this query is now out of date. The only way around this is to connection.clear_query_cache after every operation for me. This happens even in the case when the master and slave are defined as the same database -- so replication lag should not be an issue either. Any ideas?

I have a shard.yml file like this: 
```
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - production

  production:
    slave:
      host: <%= ENV['DASHBOARD_SLAVE_NAME'] %>
      password: <%= ENV['DASHBOARD_SLAVE_PASSWORD'] %>
      adapter: mysql2
      encoding: utf8
      pool: 5
      socket: /tmp/mysql.sock
```
