### ISSUE TITLE
Fully replicated isn't sending all reads to slave

### ISSUE THREAD

**Issue by drewB** [thiagopradi/octopus#440]
I have octopus setup for full replication.   I can see that some read requests are going to the slave but not others.  I know this by looking at the logs and seeing when there is a shard message or not.  Also I can see by the traffic to the slave.  Am I mistaken in thinking that ALL read requests should go to the slave?  I also saw https://github.com/thiagopradi/octopus/issues/377 so rolled back to 0.8.5 but see the same issue.

Here is my shards.yml:

 ```
octopus:
  replicated: true
  environments:
    - staging
  staging:
    slave1:
      adapter: mysql2
      host: <%= ENV['SLAVE1_DATABASE_HOST'] %>
      password: <%= ENV['DB_PASSWORD'] %>
      pool: <%= ENV['APP_POOL_SIZE'] %>
      database: my_db_name
      reconnect: true

```
