### ISSUE TITLE
How to do rails db:migrate on multiple shards at once?

### ISSUE THREAD

**Issue by suthanbala** [thiagopradi/octopus#450]
I have an app which which uses different database based on the subdomain. So essentially, the schema would be the same, but the data would differ for each databases. But when I release some new features and it would require some schema changes, I would need to run a command that would run on all databases configured in the `shards.yml`.

**database.yml**
  ```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  host: localhost
  port: 5432
  username: postgres
  password:

development:
  <<: *default
  database: app_default
production:
  <<: *default
  database: app_default
  username: <%= ENV['BACKEND_DATABASE_USERNAME'] %>
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
```

I am using Octopus to set the shard based on subdomain, which works fine. The problems I have are:

1. I cannot do `rails db:reset`
