### ISSUE TITLE
PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT ...

### ISSUE THREAD

**Issue by TimBest** [thiagopradi/octopus#457]
This error started appearing when upgrading to Rails 5.1 and octopus 0.9.1. Where a small number of queries would fail raising `PG::ConnectionBad: PQsocket() can't get socket descriptor: SELECT ...`

It looks like Rails is verifying that connections are valid when checking them out but after going through octopus the connection has closed and PQsocket() returns -1.

#### StackTrace 
```
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 73 in async_exec
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 73 in block (2 levels) in execute
rails/activesupport/lib/active_support/dependencies/interlock.rb" line 46 in block in permit_concurrent_loads
rails/activesupport/lib/active_support/concurrency/share_lock.rb" line 185 in yield_shares
rails/activesupport/lib/active_support/dependencies/interlock.rb" line 45 in permit_concurrent_loads
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 72 in block in execute
rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb" line 612 in block (2 levels) in log
.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb" line 214 in mon_synchronize
rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb" line 611 in block in log
rails/activesupport/lib/active_support/notifications/instrumenter.rb" line 21 in instrument
octopus/lib/octopus/abstract_adapter.rb" line 13 in instrument
rails/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb" line 603 in log
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 71 in execute
rails/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb" line 131 in begin_db_transaction
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 130 in initialize
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 156 in new
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 156 in block in begin_transaction
.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb" line 214 in mon_synchronize
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 152 in begin_transaction
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 193 in block in within_new_transaction
.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb" line 214 in mon_synchronize
rails/activerecord/lib/active_record/connection_adapters/abstract/transaction.rb" line 191 in within_new_transaction
rails/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb" line 235 in transaction
octopus/lib/octopus/proxy.rb" line 122 in transaction
rails/activerecord/lib/active_record/transactions.rb" line 210 in transaction
rails/activerecord/lib/active_record/transactions.rb" line 381 in with_transaction_returning_status
rails/activerecord/lib/active_record/transactions.rb" line 308 in block in save
rails/activerecord/lib/active_record/transactions.rb" line 323 in rollback_active_record_state!
rails/activerecord/lib/active_record/transactions.rb" line 307 in save
rails/activerecord/lib/active_record/suppressor.rb" line 42 in save
(Controller)
```

### System configuration
**Rails version**: 5.1.3
**Ruby version**: 2.4.1
**octopus**: 0.9.1

**Comment by Varentsov** [comment]
I'm also have this

**Comment by pboling** [comment]
I am have started seeing this as well on Rails 4.2.10 and Ruby 2.3.4.

**Comment by theirishpenguin** [comment]
I'm getting this error too and am using the octopus gem. Can't be sure it is at fault but I've ruled out a few other potential culprits.

**Comment by meysammeisam** [comment]
We are using octopus(0.9.1) on rails(5.1) and postgresql as database. We have 2 databases in master/slave replication mode.(master: read/write. slave: read-only).
When we start web server or console, everything is working and is okay, but when slave database restarts, octopus fails. seems octopus couldn't handle broken connections!
```ruby
# start rails console
Octopus.using(:slave1){ ActiveRecord::Base.connection.query('select 1;') }
#[Shard: slave1]   (0.3ms)  select 1;
#=> [[1]]

############### RESTART slave1 postgresql server ###############
Octopus.using(:slave1){ ActiveRecord::Base.connection.query('select 1;') }
#[Shard: slave1]   (0.3ms)  select 1;
#ActiveRecord::StatementInvalid: PG::ConnectionBad: PQconsumeInput() server closed the connection #unexpectedly
#        This probably means the server terminated abnormally
#        before or while processing the request.
#: select 1;

Octopus.using(:slave1){ ActiveRecord::Base.connection.query('select 1;') }
# [Shard: slave1]   (0.3ms)  select 1;
# ActiveRecord::StatementInvalid: PG::ConnectionBad: PQsocket() can't get socket descriptor: select 1;
```

Same happens on rails server and fixes just when we restart web servers.
I tested same scenario for master shard(which rails handles it) and everything is okay there. I mean, Rails finds out that the connection has been terminated and creates new connection.
Also I can reproduce it on both production(unicron) and development(thin).
`shards.yml`:
```yml
octopus:
  replicated: true
  fully_replicated: false
  environments:
    - development
    - production
  default_slave1: &default_slave1
    adapter: "postgis"
    prepared_statements: false
    reconnect: true
    encoding: unicode
    pool: "5"
    username: "username"
    password: "password"
    host: "localhost"
    port: "5433"
    database: "db_name"
  development:
    slave1:
      <<: *default_slave1
  production:
    slave1:
      <<: *default_slave1
```
`database.yml`:
```yml
default: &default
  adapter: "postgis"
  encoding: unicode
  prepared_statements: false
  pool: "5"
  username: "username"
  password: "password"
  host: "localhost"
  port: "5432"
  database: "db_name"

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
```
