### ISSUE TITLE
slave_group option does not work

### ISSUE THREAD

**Issue by andey** [thiagopradi/octopus#471]
shards.yml

```
octopus:
  replicated: true
  fully_replicated: false
  environments:
    - production

  production:
    replicas:
      slave1:
        adapter: mysql2
        host: <%= Rails.application.secrets.mysql_slave1_host %>
        database: ???????
        username: <%= Rails.application.secrets.mysql_readonly_username %>
        password: <%= Rails.application.secrets.mysql_readonly_password %>
      slave2:
        adapter: mysql2
        host: <%= Rails.application.secrets.mysql_slave2_host %>
        database: ???????
        username: <%= Rails.application.secrets.mysql_readonly_username %>
        password: <%= Rails.application.secrets.mysql_readonly_password %>
```

Using slave_group, doesn't work

```
irb(main):063:0* SmsLog.using(slave_group: :replicas).where(merchant_id: 1985).sum(:credits)
   (0.6ms)  SELECT SUM(`sms_logs`.`credits`) FROM `sms_logs` WHERE `sms_logs`.`merchant_id` = 1985
=> 0
```

Using either slave1 or slave2 directly works

```
irb(main):064:0> SmsLog.using(:slave1).where(merchant_id: 1985).sum(:credits)
[Shard: slave1]   (0.6ms)  SELECT SUM(`sms_logs`.`credits`) FROM `sms_logs` WHERE `sms_logs`.`merchant_id` = 1985
=> 0
irb(main):065:0> SmsLog.using(:slave2).where(merchant_id: 1985).sum(:credits)
[Shard: slave2]   (1.8ms)  SELECT SUM(`sms_logs`.`credits`) FROM `sms_logs` WHERE `sms_logs`.`merchant_id` = 1985
=> 0
```

Octopus looks like it's configured right, because when i use a wrong slave_group, it throws an error:

```
irb(main):010:0> SmsLog.using(slave_group: :replicassadfsadf).where(merchant_id: 1985).sum(:credits)
RuntimeError: Nonexistent Slave Group Name: replicassadfsadf in shards config: {"replicas"=>{"slave1"=>{"adapter"=>"mysql2", "host"=>"????", "database"=>"?????", "username"=>"????", "password"=>"??????"}, "slave2"=>{"adapter"=>"mysql2", "host"=>"?????", "database"=>"????", "username"=>"?????", "password"=>"???????"}}}

```
After I push this code into production, there are zero connections to the read replicas, so it was clear that Octopus wasn't actually sending any selects to either slave.

**Comment by alex-ring** [comment]
Im seeing this as well on version 0.9.2

ruby '2.3.4'
rails '5.0.1'

**Comment by rpc4mv** [comment]
Any updates on this issue?

**Comment by gabrielqueiroz** [comment]
Same issue here. Any updates on this or perhaps it changed the way that we should configure slave groups?

**Comment by gabrielqueiroz** [comment]
I don't know if that helps, but I managed to make it work on my environment. I was using YAML anchors before to reuse some defaults config, and for some reason that was making the unexpected behavior in my case.

I am currently using ruby '2.3.7' and rails '4.2.9'. My shards.yml looks like this:

```
octopus:
  replicated: true
  environments:
    - production
  production:
    followers: 
      follower_a:
        adapter: postgresql
        port: 5432
        username: ???
        password: ???
        host:     ???
        database: ???
      follower_b: 
        adapter: postgresql
        port: 5432
        username: ???
        password: ???
        host:     ???
        database: ???
```

And I get the desired outcome by specifying the slave_group:
```
irb(main):001:0> Account.last
  Account Load (0.9ms)  SELECT  "accounts".* FROM "accounts"  ORDER BY "accounts"."id" DESC LIMIT 1

irb(main):002:0> Account.using(slave_group: :followers).last
[Shard: follower_b]  Account Load (1.6ms)  SELECT  "accounts".* FROM "accounts"  ORDER BY "accounts"."id" DESC LIMIT 1

irb(main):003:0> Account.using(slave_group: :followers).last
[Shard: follower_a]  Account Load (1.5ms)  SELECT  "accounts".* FROM "accounts"  ORDER BY "accounts"."id" DESC LIMIT 1
```
