### ISSUE TITLE
Update methods sent to read-only database

### ISSUE THREAD

**Issue by swordfish444** [thiagopradi/octopus#472]
I started testing with a Live master / slave replicated database and I'm experiencing a seemingly random set of ActiveRecord update methods be incorrectly sent to the Read-only database. As one would expect, this fails. I'm using Rails 5.1.4 and Ruby 2.5.0 and have ran into no issues up until this point. 

@thiagopradi Do you have any suggestions on where this may be arising from? I've reviewed all the open PRs and Issues and it appears that there are a number of issues with the reverse happening -- selects being sent to the master. 

Here is an example w/ the error to help demonstrate:

```ruby        
foo = Foo.find(params[:id])
foo.update_attributes(params)

# ---- Throws the following exception ----
# Mysql2::Error: The MySQL server is running with the --read-only option so it cannot execute this statement
# ActiveRecord::StatementInvalid: Mysql2::Error: The MySQL server is running with the --read-only option so it cannot execute this statement: UPDATE `foo` SET `bar` = 0.0, `updated_at` = '2018-02-07 19:42:46' WHERE `foo`.`id` = 123
```

Here is what my shards.yml looks like as its possible I could have it incorrect. Removed connection details for brevity. The intent behind this configuration is to send all SELECTS to the **readonly** and everything else to the **master**.

```yaml
octopus:
  master_shard: master
  replicated: true
  fully_replicated: true
  verify_connection: true
  environments:
    - development
  development:
    master:
      adapter: mysql2
    readonly:
      adapter: mysql2
```
