### ISSUE TITLE
Rake test:units fails

### ISSUE THREAD

**Issue by pmatsinopoulos** [thiagopradi/octopus#65]
It seems that there is a problem that is related to "environments" tag inside the shards.yml file. It confuses "rake" which incorrectly uses development database instead of test database to run tests.

The shards.yml file that I use is the following: 

```
octopus:
  replicated: true
  fully_replicated: false
  verify_connection: true
  environments:
    - development
  development:
    slave1:
      adapter: mysql2
      encoding: utf8
      reconnect: false
      database: shop_development
      pool: 5
      username: root
      password:
      host: 10.0.0.122
```
