### ISSUE TITLE
Quoting in multiple databases(MySQL and Oracle)

### ISSUE THREAD

**Issue by tnedlacer** [thiagopradi/octopus#87]
Report the issue that occurred in my environment.

database.yml

``` yaml
production:
  adapter: mysql2
production_oracle:
  adapter: oracle_enhanced
```

shard.yml

``` yaml
octopus:
  environments:
    - production
  production:
    slave1:
      adapter: mysql2
```

oracle_a.rb

``` ruby
class OracleA < ActiveRecord::Base
  self.octopus_establish_connection configurations["#{Rails.env}_oracle"]
end
```

Oracle's data call

``` ruby
OracleA .count
#=> OCIError: ORA-00911: SELECT COUNT(*) FROM `DB`.`OracleA`
```

Quart of Oracle: "
Quart of MySQL: `

lib/octopus/rails3/arel.rb

``` ruby
class Arel::Visitors::ToSql
  def quote_table_name name
    ActiveRecord::Base.connection.quote_table_name(name)
    # ActiveRecord::Base == MySQL
  end
end
```

remove this code

``` ruby
class Arel::Visitors::ToSql
=begin
  ...
  ...
=end
end
```

``` ruby
OracleA .count
#=> SELECT COUNT(*) FROM "DB"."OracleA" 
```
